- azure-pipelines.yaml
- components/general/app-gateway.tf
- components/general/inputs-optional.tf
- components/general/inputs-required.tf
- components/general/public-ip.tf
- environments/nonprod/nonprod.tfvars
See [jira](https://tools.hmcts.net/jira/browse/DTSPO-22113)
Config to add non production application gateway for atlassian apps.
> DTSPO-22113 - adding appgw

- components/general/app-gateway.tf
- components/general/inputs-required.tf
- environments/nonprod/nonprod.tfvars
Added missing SSL certificate config
> added certificate config

- .github/CODEOWNERS
- components/general/app-gateway.tf
- components/general/inputs-optional.tf
- environments/nonprod/nonprod.tfvars
- renovate.json
Added few further config as well as coddeowners and renovate json.
> Add codeowners renovate

- components/general/app-gateway.tf
- components/general/inputs-required.tf
- environments/nonprod/nonprod.tfvars
Trying to fix the issue with routing rule.
> Trying to fix the issue with routing rule

- components/general/app-gateway.tf
- components/general/inputs-required.tf
- environments/nonprod/nonprod.tfvars
Reverts hmcts/atlassian-infrastructure#6
> Revert "Trying to fix the issue with routing rule"

- components/general/app-gateway.tf
Fixing issue with the routing rule
> Fixing routing rule issue

- components/general/inputs-required.tf
- components/general/storage-account.tf
- environments/nonprod/nonprod.tfvars
Creating storage account to restore the VMs.
> Added config to rollout storage account

- components/general/keyvault.tf
- environments/nonprod/nonprod.tfvars
Adding f5 VPN to be able to ssh to the VMs.
> allow VPN access for the VMs to ssh them

- components/general/db.tf
- components/general/init.tf
> DTSPO-22117 - add db single server recreation

- components/general/db.tf
- environments/nonprod/nonprod.tfvars
> Changing source IP address for VPN access

- components/general/db.tf
DTSPO-22117 
Add dbs to single server
> DTSPO-22117 - Add dbs to single server

- components/general/db.tf
DTSPO-22117
Resize DB to General Purpose instead of Basic SKU
> DTSPO-22117 - Resize DB to General Purpose instead of Basic SKU

- components/general/db.tf
> Change the sotrage MB

- components/general/db.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22116
Updated NSG rules to allow VPN access on atlassian-int-subnet-dat subnet
> Added VPN access nsg rule for the atlassian-int-subnet-dat

- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22585
Updated backend IPs to the real VM ips.
> DTSPO-22585 - updated backend to the VM ips

- components/general/app-gateway.tf
https://tools.hmcts.net/jira/browse/DTSPO-22585
Updated Application gateway settings
> Updated application gateway config

- components/general/keyvault.tf
Fix errors raised on the pipeline
> fix errors on the pipeline

- components/general/inputs-optional.tf
- components/general/interpolated-defaults.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22585
Updated backend IP addresses of Jira VM after re-deploying them.
> DTSPO-22585 - Updated Atlassian app gateway IP address

- components/general/db.tf
Trying to fix the private end point not resolving issue on the postgres nonprod sever.
> trying to fix the Private end point

- components/general/load_balancer.tf
- environments/nonprod/nonprod.tfvars
> DTSPO-22862 - Fix few problems on the pipeline

- components/general/app-gateway.tf
- components/general/inputs-optional.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22917
Disabled rules as they were false positive.
> DTSPO-22917 - Disabled WAF rules as they were false positive

- components/general/app-gateway.tf
- components/general/db.tf
- components/general/inputs-optional.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22917
Changed WAF to use the waf firewall policy to match with production
> Added the changes for the WAF

- components/general/vm.tf
- environments/nonprod/nonprod.tfvars
See [Jira](https://tools.hmcts.net/jira/browse/DTSPO-23026)
Testing config script on Jira Vms
> DTSPO-23026 - jira VMs config changes

- components/general/scripts/configure-jira-vm.sh
- components/general/vm.tf
Trying to get the VM config file working on the VMs.
> Script debugging

- components/general/scripts/configure-jira-vm.sh
- environments/nonprod/nonprod.tfvars
Adding more script changes after its started working.
Also, setting Auto shutdown to false to perform re-index for the weekend.
> Adding further script changes

- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/functions.sh
- components/general/vm.tf
https://tools.hmcts.net/jira/browse/DTSPO-23026
Allows script to uninstall Dynatrace from the staging VMs.
> Uninstalling Dynatrace from the jira VMs

- components/general/inputs-optional.tf
- components/general/scripts/configure-jira-vm.sh
- components/general/vm.tf
- environments/nonprod/nonprod.tfvars
> Dynatrace Debug

- components/general/db.tf
- components/general/inputs-optional.tf
- components/general/inputs-required.tf
- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-jira-vm.sh
- components/general/vm.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-23026 
Adding config for the Crowd VMs
> DTSPO-23026 - Added config changes for Crowd

- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-gluster-vm.sh
- components/general/vm.tf
Added automation script for the Gluster VMs
> DTSPO-23026 - Adding script config changes for the gluster VM

- components/general/db.tf
- components/general/scripts/configure-confluence-vm.sh
- components/general/vm.tf
https://tools.hmcts.net/jira/browse/DTSPO-23026
Added script changes for the confluence VMs too.
> Added config changes for Confluence

- components/general/scripts/functions.sh
Updated time for the cron job from being 8am to 7:15am as some teams starts early.
> Updated Cronjob timing after discussion with Atlassian team

- components/general/scripts/configure-confluence-vm.sh
- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/functions.sh
Due to recent issue on Auto Shutdown process with Github, we decided to run this cron job every hour. dont think it will harm anything.
Issue - https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1737536658092309
> Change mounting to mount every hour

- components/general/db.tf
Updating postgres single Server SKU to match what we have on production.
> Updated postgres server SKU to match production

- components/general/app-gateway.tf
- components/general/inputs-optional.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-23646
Adding rewrite rule which is already present in PRP environment. This is to align the staging env for on-going development work.
Feature flag defaulted to false added to ensure prod only gets this change if / when needed during its deployment.
- Tested via portal
- Feature flag tested
> DTSPO-23646 - Adding Rewrite Ruleset to match current PRP env

- components/general/db.tf
- components/general/inputs-optional.tf
- environments/nonprod/nonprod.tfvars
DTSPO-23191
Deploying flex server for migration
> DTSPO-23191 adding flex server for migration

- components/general/db.tf
- environments/nonprod/nonprod.tfvars
DTSPO-23191
Deploy new subnet for flex server due to private endpoint on existing subnet.
> DTSPO-23191 - Deploy new subnet for flex server

- components/general/db.tf
- components/general/scripts/configure-jira-vm.sh
- components/general/vm.tf
- environments/nonprod/nonprod.tfvars
DTSPO-23191
Following the single to flex serve migration, the VM's will need to have the configuration scripts run to set to the new Flex server.
app_action has been set to stop to perform a restart of the application.
> DTSPO-23191 - updating scripts for flex server migration

- environments/nonprod/nonprod.tfvars
DTSPO-23191
correcting rule priority for ops-nsg
> DTSPO-23191 - correcting rule priority for ops-nsg

- components/general/scripts/configure-jira-vm.sh
- components/general/vm.tf
DTSPO-23191
updating jira username
> DTSPO-23191 - updating jira username

- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/robots_template.txt
- environments/nonprod/nonprod.tfvars
- environments/prod/prod.tfvars
DTSPO-23913
- Setting rewrite to case sensitive
- Adding template file to deploy robots.txt file
> DTSPO-23913 - Setting rewrite to case sensitive

- components/general/backups.tf
See [DTSPO-24311](https://tools.hmcts.net/jira/browse/DTSPO-24311)
Enable recovery services vault in stg also
Initially only created this for new prod, but an RSV exists in the current prod that covers PRP as well
> DTSPO-24311 - Enable RSV in stg

- components/general/db.tf
- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/configure-postgres.sh
DTSPO-24225
triggering db setup script
> DTSPO-24225 - triggering db setup script

- components/general/db.tf
- environments/prod/prod.tfvars
DTSPO-24225
- removing atlassian restart flag
- removing DB script trigger
> DTSPO-24225 - Tidy up, removing atlassian restart flag

- azure-pipelines.yaml
- components/general/scripts/configure-confluence-vm.sh
- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-gluster-vm.sh
- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/functions.sh
[DTSPO-24512](https://tools.hmcts.net/jira/browse/DTSPO-24512)
adding function to update NTP servers to use azure servers for stg
> DTSPO-24512 adding function to change ntp servers to azure servers

- azure-pipelines.yaml
- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/robots_template.txt
DTSPO-24513
Updating scripts to add a blank line at the end of the robots.txt file.
> DTSPO-24513 - robots.txt blank line

- components/general/scripts/configure-confluence-vm.sh
- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-gluster-vm.sh
- components/general/scripts/configure-jira-vm.sh
[DTSPO-24512](https://tools.hmcts.net/jira/browse/DTSPO-24512)
Changing ntp scripts to run on all environments.  This is for change request at 1pm today to fix the time sync issue on prod vm's
> DTSPO-24512 changing ntp scripts to run on all environments

- azure-pipelines.yaml
- components/general/app-gateway.tf
- components/general/scripts/configure-confluence-vm.sh
- components/general/scripts/configure-crowd-vm.sh
- components/general/scripts/configure-jira-vm.sh
- components/general/scripts/functions.sh
- components/general/vm.tf
- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-24733
- Updating app gateway to pass the ssl certificate data instead of the key vault id
- Hoping this prevents auto-renewal outside of pipeline runs
- Also updated scripts to add certs to confluence and crowd servers as well as jira
> Dtspo 24733 ssl auto renewal

- components/general/app-gateway.tf
https://tools.hmcts.net/jira/browse/DTSPO-24733
- Accidentally named the new ssl cert wrong
- Changing from `staging-tools-hmcts-net` to `staging.tools.hmcts.net`
> Update ssl certificate name

- components/general/scripts/configure-crowd-vm.sh
- components/general/vm.tf
- Scripts ran before the application gateway updated with the new cert
- Adding `depends_on` to prevent this from happening in future
> Add depends_on to terraform_data resource

- components/general/scripts/functions.sh
- Changing location crowd certs to `/etc/pki/java/cacerts` as both Java installations are symlinked to here
> Updating crowd script to store certs in /etc/pki/java/cacerts

- azure-pipelines.yaml
https://tools.hmcts.net/jira/browse/DTSPO-24733
- Re-enabling the prod step in the pipeline
- Happy with SSL cert renewal process after testing in staging manually and via automation
> Re-enable prod pipeline step

- components/general/db.tf
- components/general/vm.tf
- Creating a temporary PostgreSQL Flexible Server in staging
- This will be a PITR of the original server
- Not replicating the `terraform_data` resource for this server as it is only temporary
- Also adding `os_profile` and `os_profile_linux_config` to lifecycle `ignore_changes` as pipeline keeps trying to remove them and we don't use them
> Create temp postgres server in staging

- components/general/db.tf
- environments/nonprod/nonprod.tfvars
- Upgraded temp server from pg `11` -> `15` and now restoring it to a new permanent v15 server
- Also adding `point_in_time_restore_time_in_utc` to `ignore_changes` on the temp server to prevent re-creation
- Also had to add a `Microsoft.Storage` service endpoint to a nonprod subnet as Terraform was trying to remove it
> Restore upgraded staging server

- components/general/db.tf
- Removing the temp staging server 
- Adding a new `terraform_data` resource for nonprod-v15 server
- Had to separate out v15 stuff into separate resources for nonprod and prod due to the fact we're using PITR and the source server will differ between each. Same applies to `terraform_data` here
> Dtspo 24713 remove temp

- components/general/backups.tf
- Creating a backup vault in staging to test backup and restore
- Testing on the v15 database first as it isn't in use currently
> Create backup vault

- components/general/backup.tf
- Accidentally removed the VM rsv when trying to remove the postgres backup vault
- Adding the vault back to code
- Recreating the backup policy
- Importing the backup items into tf state after recovering via portal
> Re-add rsv that was accidentally removed

- azure-pipelines.yaml
- components/general/db.tf
- components/general/scripts/backup-postgres.sh
- components/general/scripts/restore-postgres.sh
- Updating backup script to accept host argument in the case we want to backup from another server
- Updating restore script to create the new db with collation `en_US.UTF-8` as default is not supported by new Jira version
- Also changing pipeline to run on Wednesday instead of Monday as prod cert is due to renew on a bank holiday
- Also ignoring changes on `administrator_login` on new DB, same as original
> Add host arg to backup script

- azure-pipelines.yaml
- Reverting pipeline to run automatically on Monday
- Had changed to Wednesday in case it ran on the bank holiday and didn't work but it ran this morning and updated the cert as expected so confident there will be no issues with this going forward
> Revert pipeline to run on Monday

- environments/nonprod/nonprod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25256
Getting this ready before I start backup-restore procedure
**DO NOT MERGE UNTIL THIS IS DONE**
N/A
> Point both confluence servers at v15 postgres
